=== Ingvord/JTangoTestDevice/api/java/tags/javaweb/release_0_0_3/server/config/serializationConfig.dtd
<!-- DTD For Tango Web Server Mapping -->
<!ELEMENT config (beans, rewriterules)>
<!-- Beans contains all beans which could be used  as Data Access Object or Data Object -->
<!-- Serializable Data Object aren't be mandatory-->
<!ELEMENT beans (bean+)>
<!ELEMENT bean (className, storeObject, optimizedStorage, removeAllAttributes, removeAttributes?, attributes?)>
<!-- bean and uniqueid for the bean -->
<!ATTLIST bean 
		id ID #REQUIRED>
<!-- className contains complete Name : package.class-->		
<!ELEMENT className (#PCDATA)>
<!-- store the object in the server session for futur use ?-->
<!ELEMENT storeObject (#PCDATA)>
<!-- If storeObject is	equal to True, we store this object into a special Storage whith optimization -->
<!ELEMENT optimizedStorage (#PCDATA)>
<!-- remove all attribute before serialization ?-->
<!ELEMENT removeAllAttributes (#PCDATA)>
<!-- attributes list name to remove before serialization-->
<!ELEMENT removeAttributes (removeAttribute*)>
<!-- attributes name to remove before serialization -->
<!ELEMENT removeAttribute (#PCDATA)>
<!ATTLIST removeAttribute 
		name NMTOKEN #REQUIRED>
<!ELEMENT getSuperClassAttributes (#PCDATA)>
<!ELEMENT attributes (attribute*)>
<!ELEMENT attribute (#PCDATA)>
<!ATTLIST attribute 
		id IDREF #IMPLIED
		name NMTOKEN #REQUIRED>
<!-- Rewrite rules, some class in Client Application extends beans classes -->
<!-- This section define transform rule, for server. -->
<!-- if a class coresponding to a src class will be present, it will be transform into the coresponding dest class -->
<!ELEMENT rewriterules (rule+)>
<!ELEMENT rule (src, dest)>
<!-- src : contains the complete class name : package.class -->
<!ELEMENT src (#PCDATA)>
<!-- dest : contains the complete class name : package.class -->
<!ELEMENT dest (#PCDATA)>

=== Ingvord/JTangoTestDevice/api/java/trunk/javaweb/server/config/serializationConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE XML SYSTEM "serializationConfig.dtd">
<config>
	<beans>
		<bean id="DeviceAttribute">
			<className>fr.esrf.TangoApi.DeviceAttribute</className>
			<!-- true / false--> 
			<storeObject>true</storeObject>
			<optimizedStorage>true</optimizedStorage>
			<!-- true / false--> 
			<removeAllAttributes>false</removeAllAttributes>
			<removeAttributes>
				<removeAttribute name="deviceattributeDAO"></removeAttribute>
			</removeAttributes>
			<attributes>
				<attribute name="attrval" id="AttributeValue_3"></attribute>
			</attributes>
		</bean>
		<bean id="AttributeValue">
			<className>fr.esrf.Tango.AttributeValue</className>
			<!-- true / false--> 
			<storeObject>false</storeObject>
			<optimizedStorage>false</optimizedStorage>
			<!-- true / false--> 
			<removeAllAttributes>false</removeAllAttributes>
			<removeAttributes>
				<removeAttribute name="value"></removeAttribute>
			</removeAttributes>
			<attributes/>
		</bean>
		<bean id="AttributeValue_3">
			<className>fr.esrf.Tango.AttributeValue_3</className>
			<!-- true / false--> 
			<storeObject>false</storeObject>
			<optimizedStorage>false</optimizedStorage>
			<!-- true / false--> 
			<removeAllAttributes>false</removeAllAttributes>
			<removeAttributes>
				<removeAttribute name="value" />
			</removeAttributes>
			<attributes/>
		</bean>	
		<bean id="Database">
			<className>fr.esrf.TangoApi.Database</className>
			<!-- true / false--> 
			<storeObject>true</storeObject>
			<optimizedStorage>false</optimizedStorage>
			<!-- true / false--> 
			<removeAllAttributes>true</removeAllAttributes>
			<removeAttributes/>
			<attributes/>
		</bean>
		<bean id="DeviceData">
			<className>fr.esrf.TangoApi.DeviceData</className>
			<!-- true / false--> 
			<storeObject>true</storeObject>
			<optimizedStorage>false</optimizedStorage>
			<!-- true / false--> 
			<removeAllAttributes>false</removeAllAttributes>
			<removeAttributes>
				<removeAttribute name="devicedataDAO"></removeAttribute>
				<removeAttribute name="any"/>
			</removeAttributes>
			<attributes/>
		</bean>
		<bean id="ApiUtil">
			<className>fr.esrf.TangoApi.ApiUtil</className>
			<!-- true / false--> 
			<storeObject>true</storeObject>
			<optimizedStorage>false</optimizedStorage>
			<!-- true / false--> 
			<removeAllAttributes>true</removeAllAttributes>
			<removeAttributes/>
			<attributes/>
		</bean>		
		<bean id="DeviceProxy">
			<className>fr.esrf.TangoApi.DeviceProxy</className>
			<!-- true / false--> 
			<storeObject>true</storeObject>
			<optimizedStorage>false</optimizedStorage>
			<!-- true / false--> 
			<removeAllAttributes>true</removeAllAttributes>
			<removeAttributes/>
			<attributes/>
		</bean>
		<bean id="IORDump">
			<className>fr.esrf.TangoApi.IORdump</className>
			<!-- true / false--> 
			<storeObject>true</storeObject>
			<optimizedStorage>false</optimizedStorage>
			<!-- true / false--> 
			<removeAllAttributes>true</removeAllAttributes>
			<removeAttributes>
				<removeAttribute name="iordumpDAO"></removeAttribute>
			</removeAttributes>			
			<attributes/>
		</bean>		
		<bean id="DeviceDataHistory">
			<className>fr.esrf.TangoApi.DeviceDataHistory</className>
			<!-- true / false--> 
			<storeObject>true</storeObject>
			<optimizedStorage>false</optimizedStorage>
			<!-- true / false--> 
			<removeAllAttributes>false</removeAllAttributes>
			<removeAttributes>
				<removeAttribute name="devicedatahistoryDAO"></removeAttribute>
				<removeAttribute name="any"/>
			</removeAttributes>
			<attributes>
				<attribute name="cmd_histo" id="DevCmdHistory"></attribute>
			</attributes>
		</bean>
		
		<bean id="DevCmdHistory">
			<className>fr.esrf.Tango.DevCmdHistory</className>
			<!-- true / false--> 
			<storeObject>true</storeObject>
			<optimizedStorage>false</optimizedStorage>
			<!-- true / false--> 
			<removeAllAttributes>false</removeAllAttributes>
			<removeAttributes>
				<removeAttribute name="value"/>
			</removeAttributes>
			<attributes/>
		</bean>
		
		
		<bean id="ArchivingManagerFacade">
			<className>fr.soleil.mambo.web.db.ArchivingManagerFacade</className>
			<!-- true / false--> 
			<storeObject>false</storeObject>
			<optimizedStorage>false</optimizedStorage>
			<!-- true / false--> 
			<removeAllAttributes>false</removeAllAttributes>
			<removeAttributes />
			<attributes/>
		</bean>
		<bean id="AttributeManagerFacade">
			<className>fr.soleil.mambo.web.db.AttributeManagerFacade</className>
			<!-- true / false--> 
			<storeObject>false</storeObject>
			<optimizedStorage>false</optimizedStorage>
			<!-- true / false--> 
			<removeAllAttributes>false</removeAllAttributes>
			<removeAttributes />
			<attributes/>
		</bean>
		<bean id="ExtractingManagerFacade">
			<className>fr.soleil.mambo.web.db.ExtractingManagerFacade</className>
			<!-- true / false-->
			<storeObject>false</storeObject>
			<optimizedStorage>false</optimizedStorage>
			<!-- true / false--> 
			<removeAllAttributes>false</removeAllAttributes>
			<removeAttributes />
			<attributes/>
		</bean>
		<bean id="Connection">
			<className>fr.esrf.TangoApi.Connection</className>
			<storeObject>false</storeObject>
			<optimizedStorage>false</optimizedStorage>
			<removeAllAttributes>true</removeAllAttributes>
			<removeAttributes />
			<attributes/>
		</bean>	
		<bean id="DeviceProxyDAOMachineStatusInterceptor">
			<className>fr.soleil.atkwebserver.machinestatus.DeviceProxyDAOMachineStatusInterceptor</className>
			<storeObject>false</storeObject>
			<optimizedStorage>false</optimizedStorage>
			<removeAllAttributes>true</removeAllAttributes>
			<removeAttributes />
			<attributes/>
		</bean>
	</beans>
	<rewriterules>
		<rule>
			<src>mambo.datasources.db.archiving.WebArchivingManager</src>
			<dest>fr.soleil.mambo.web.db.ArchivingManagerFacade</dest>
		</rule>
		<rule>
			<src>mambo.datasources.db.attributes.WebAttributeManager</src>
			<dest>fr.soleil.mambo.web.db.AttributeManagerFacade</dest>
		</rule>
		<rule>
			<src>mambo.datasources.db.extracting.WebExtractingManager</src>
			<dest>fr.soleil.mambo.web.db.ExtractingManagerFacade</dest>
		</rule>
		<rule>
			<src>admin.astor.DbaseObject$DbConnection</src>
			<dest>fr.esrf.TangoApi.Connection</dest>
		</rule>
		<rule>
			<src>fr.esrf.web.TangoApi.tangorbversion.TangORBversionWebImpl</src>
			<dest>fr.esrf.TangoApi.tangorbversion.TangORBversionDefaultImpl</dest>					
		</rule>
		<rule>
			<src>fr.esrf.TangoApi.DeviceProxyDAOWebImpl</src>
 			<dest>fr.esrf.TangoApi.DeviceProxy</dest>
			<!-- <dest>fr.soleil.atkwebserver.machinestatus.DeviceProxyDAOMachineStatusInterceptor</dest>					 -->
		</rule>
		<rule>
			<src>fr.esrf.TangoApi.ConnectionDAOWebImpl</src>
			<dest>fr.esrf.TangoApi.Connection</dest>		
		</rule>
		<rule>
			<src>fr.esrf.TangoApi.DatabaseDAOWebImpl</src>
			<dest>fr.esrf.TangoApi.Database</dest>		
		</rule>		
		<rule>
			<src>fr.esrf.TangoApi.DeviceAttributeDAOWebImpl</src>
			<dest>fr.esrf.TangoApi.DeviceAttribute</dest>		
		</rule>		
		<rule>
			<src>fr.esrf.TangoApi.DeviceDataDAOWebImpl</src>
			<dest>fr.esrf.TangoApi.DeviceData</dest>		
		</rule>		
		<rule>
			<src>fr.esrf.TangoApi.DeviceDataHistoryDAOWebImpl</src>
			<dest>fr.esrf.TangoApi.DeviceDataHistory</dest>		
		</rule>		
		<rule>
			<src>fr.esrf.TangoApi.ApiUtilDAOWebImpl</src>
			<dest>fr.esrf.TangoApi.ApiUtil</dest>		
		</rule>		
		<rule>
			<src>fr.esrf.TangoApi.IORDumpDAOWebImpl</src>
			<dest>fr.esrf.TangoApi.IORdump</dest>	
		</rule>
	</rewriterules>
</config>
